repos:
-   repo: https://github.com/python/black
    rev: 23.9.1  # Use the latest version or a specific version
    hooks:
      - id: black
        args: [--line-length, '79']
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort